server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:6500/uedb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: 4D6251655468576D5A7134743777217A25432A462D4A614E645266556A586E32
  expiration: 86400000


services:
  registration:
    url: http://20.84.34.69/registration-service
  authentication:
    url: https://biometric-sdk-svc-docker.onrender.com/
